#!/bin/bash

echo "===================================="
echo "Sửa chữa quyền widget..."
chown -R mobile:mobile /var/mobile/Library/LockHTML 2>&1
chown -R mobile:mobile /var/mobile/Library/SBHTML 2>&1
chown -R mobile:mobile /var/mobile/Library/iWidgets 2>&1
chown -R mobile:mobile /var/mobile/Library/Widgets 2>&1

chmod -R 0755 /var/mobile/Library/LockHTML 2>&1
chmod -R 0755 /var/mobile/Library/SBHTML 2>&1
chmod -R 0755 /var/mobile/Library/iWidgets 2>&1
chmod -R 0755 /var/mobile/Library/Widgets 2>&1
echo "Quyền cố định."
echo "Cài đặt lại Xen HTML Nếu bạn gặp cảnh báo 'Quyền Sửa lỗi' khi thay đổi cài đặt Widget."

# Handle the daemon
echo "(Re)-Đang tải Daemon...."
chown root /Library/LaunchDaemons/com.matchstic.widgetinfod.plist

# Unload for an upgrade. - Might spew an error, so hide that.
/bin/launchctl unload /Library/LaunchDaemons/com.matchstic.widgetinfod.plist 2>/dev/null || /sbin/launchctl unload /Library/LaunchDaemons/com.matchstic.widgetinfod.plist 2>/dev/null
/bin/launchctl load /Library/LaunchDaemons/com.matchstic.widgetinfod.plist 2> /dev/null || /sbin/launchctl load /Library/LaunchDaemons/com.matchstic.widgetinfod.plist

# Clear debug logs if present
if [ -d "/var/mobile/Library/Logs/Xen-HTML" ]; then rm -Rf /var/mobile/Library/Logs/Xen-HTML; fi
    
# Clear old symlink if present
[ -e "/var/mobile/Library/SBHTML/Background | Kaleidoscope" ] && rm "/var/mobile/Library/SBHTML/Background | Kaleidoscope"
[ -e "/var/mobile/Library/SBHTML/Background | Particles" ] && rm "/var/mobile/Library/SBHTML/Background | Particles"

echo "===================================="
echo "Biên dịch bởi:"
echo "TRƯƠNG TAM PHONG"
echo "===================================="
echo "	"
echo "Cảm ơn bạn đã sử dụng tinh chỉnh này."
